common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
path('logout/', auth_views.LogoutView.as_view(), name='logout'),
path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 경로 추가

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('question/', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    path('', base_views.main, name='main'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('vote/answer/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default='', related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가
    view_count = models.IntegerField(default=0)  # 조회수 필드 추가
    price = models.IntegerField()
    image = models.ImageField(upload_to='images/', null=True, blank=True)  # 이미지 필드 추가

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'image', 'price']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
            'image': '이미지',
            'price': '가격',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user in answer.voter.all():
        answer.voter.remove(request.user)
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..models import Question, QuestionCount


def get_client_ip(request):  # Add this function
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

def main(request):
    return render(request, 'pybo/mainpage.html')



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    ip = get_client_ip(request)
    #cnt = QuestionCount.objects.filter(ip=ip, question=question).count()
    #if cnt == 0:
       # qc = QuestionCount(ip=ip, question=question)
        #qc.save()
        #if question.view_count:
        #    question.view_count += 1
        #else:
           # question.view_count = 1
       # question.save()
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.price = form.cleaned_data['price']
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/mainpage.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% load time_since %}
{% block content %}
{% load static%}

<style>
    .image-container {
        display: flex;
        justify-content: center;
    }

    .image-container img {
        max-width: 100%;
        height: auto;
    }
</style>

<div class="image-container">
    <img src="{% static '/image/main1.jpg' %}" alt="ERROR">
</div>

<a href="{% url 'common:login' %}">로그인</a>
<head>
    <title>충대마켓</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        p {
            text-align: center;
            font-size: 18px;
            color: #555;
        }

        .link {
            display: block;
            width: 200px;
            margin: 20px auto;
            padding: 10px;
            text-align: center;
            font-size: 18px;
            color: #fff;
            background-color: #007bff;
            border-radius: 5px;
            text-decoration: none;
        }

        .link:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>충대마켓</h1>
        <p>누구나 이용 가능한 중고마켓 장터! 충대마켓 입니다.</p>
        <a class="link" href="{% url 'pybo:index' %}">물건 보러 가기</a>
    </div>
</body>

{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% load time_since %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}

<style>
    table {
        margin-left: auto;
        margin-right: auto;
        width: 800pt;
        height: 250pt;
    }

    table,
    th,
    td {
    }

    colgroup {
        width: 100%;
        height: 100%;
    }

    col.col1 {
        width: 0%;
    }

    col.col2 {
        width: 5%;
    }

    col.col3 {
        width: 90%;
    }

    .container {
        max-width: 80rem;
        margin: 0 auto;
    }

    .alert {
        padding: 1rem;
        margin-bottom: 1rem;
    }

    .card {
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .card-body {
        padding: 1rem;
        height: 130pt;
    }

    .card-text {
        margin-bottom: 1rem;
    }

    .badge {
        font-size: 0.8rem;
        padding: 0.25rem 0.5rem;
    }

    .my-3 {
        margin-top: 1rem;
        margin-bottom: 1rem;
        clear: both;
    }

    .btn {
        display: inline-block;
        padding: 0.25rem 0.5rem;
        font-size: 1.2rem;
        border-radius: 4px;
        text-decoration: none;
        cursor: pointer;
    }

    .btn-outline-secondary {
        color: #6c757d;
        border-color: #6c757d;
    }

    .btn-outline-secondary:hover {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }

    .rounded-pill {
        border-radius: 50rem;
    }

    #left-section {
        width: 60%;
        padding: 10px;
        float: left;
    }

    #right-section {
        width: 40%;
        padding: 10px;
        float: right;
    }
</style>

    <p>&nbsp;</p>
<table>
    <colgroup>
        <col class="col1">
        <col class="col2">
        <col class="col3">
    </colgroup>
    <tbody>
        <tr>
            <td rowspan="5">
                <img src="{{ question.image.url }}" style="width: 500px; height: 500px" alt="{{ question.subject }}"
                    class="my-3">
            </td>
            <td rowspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>
                <h1>{{ question.subject }}</h1>
            </td>
        </tr>
        <tr>
            <td>
                <p class="border-bottom py-1">
                    <span style="font-size: 2.5rem; font-weight: bold;">{{ question.price }}</span>
                    <span style="font-size: 1.5rem;">원</span>
                </p>
            </td>
        </tr>
        <td>
            <div class="d-flex">
                <div>
                    <p style="color: #C0C0C0;">♥: {{question.voter.count}} |&nbsp;</p>
                </div>
                <div>

                    <div>
                        <div style="color: #C0C0C0;">▶:{{ question.create_date|time_since }}</div>
                    </div>

        <tr>
            <td>
<p>&nbsp;</p><p>&nbsp;</p>
            </td>
        </tr>
        <tr>
            <td>
                <div class="my-3" style="display: flex; align-items: center;">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}"
                        class="recommend btn btn-sm btn-outline-secondary"
                        style="background-color: blue; color: white; font-size: 2rem; font-weight: bold; padding: 0.5rem 1rem; padding-left: 4rem; padding-right: 4rem;">
                        ♥찜
                    </a>
                     &nbsp; &nbsp;
                                        <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}"
                        class="recommend btn btn-sm btn-outline-secondary"
                        style=" font-size: 2rem; font-weight: bold; padding: 0.5rem 1rem; padding-left: 4rem; padding-right: 4rem;">
                        충톡
                    </a>

                </div>
                <div class="my-3" style="margin-left: auto;">
                        {% if request.user == question.author %}
                        <a href="{% url 'pybo:question_modify' question.id  %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                        {% endif %}
                    </div>
            </td>
        </tr>
        <tr>
        </tr>
    </tbody>
</table>





<!-- 답변 -->

<hr style="border: solid 1px black;">

<div class="row">
    <div class="col-md-4">
        <h5 class="border-bottom py-2">상품설명</h5>
        <div class="card my-3 left-section">
            <div class="card-body">
                <div class="card-text">
                    <h6 style="font-weight: bold;">{{ question.content|mark }}</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <h5 class="border-bottom py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
        <div class="answer-container">
            {% for answer in question.answer_set.all %}
            <a id="answer_{{ answer.id }}"></a>
            <div class="answer-card card my-3">
                <div class="card-body">
                    <div class="answer-content card-text">
                        <span class="answer-author" style="font-weight: bold;">[ {{ answer.author.username }} ]</span>{{ answer.content|mark }}
                    </div>
                    <hr>
                    <div class="answer-meta">
                        {% if answer.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3" style="border: 0.1px solid #000;font-size: 1.5rem;">
                            <div>수정됨: {{ answer.modify_date }}</div>
                        </div>
                        {% else %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3" style="border: 0.5px solid #000;font-size: 1.5rem;">
                            <div>{{ answer.create_date }}</div>
                        </div>
                        {% endif %}
                        <div class="answer-buttons my-3">
                            <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}"
                                class="recommend btn btn-sm btn-outline-secondary"> 추천
                                <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                            </a>
                            {% if request.user == answer.author %}
                            <a href="{% url 'pybo:answer_modify' answer.id  %}"
                                class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                                data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


<style>
    .answer-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .answer-card {
        flex-basis: 100%; /* 원하는 카드 너비로 조정 */
        margin-bottom: 20px;
        padding: 15px;
        border: 1px solid #ddd;
        border-radius: 4px;
        background-color: #f9f9f9;
        overflow: auto; /* 스크롤 생성 */
    }

    .answer-content {
        margin-bottom: 10px;
        max-height: 200px;
    }

    .answer-meta {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
    }

    .answer-meta .badge {
        font-size: 0.8rem;
        padding: 0.25rem 0.5rem;
    }

    .answer-buttons {
        display: flex;
    }

    .answer-buttons .btn {
        margin-right: 5px;
    }

    .left-section {
        padding: 10px;
    }

    .right-section {
        padding: 10px;
    }
</style>




<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
        <label for="content" class="form-label">답변내용</label>
        <textarea {% if not user.is_authenticated %}disabled{% endif %}
                  name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">
</form>
</div>
{% endblock %}
{% block script %}


<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">제품등록</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="image" class="form-label">제품사진</label>
            <input type="file" class="form-control" name="image" id="image">
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">가격</label>
            <input type="number" class="form-control" name="price" id="price">
        </div>
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% load time_since %}
{% block content %}
<a href="{% url 'pybo:main' %}">제품 등록하기</a>

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">제품 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <h1>최근 올라온 상품</h1>
    <div class="row">
        {% if question_list %}
            {% for question in question_list %}
                <div class="col-4">
                    <div class="item">
                        <div class="card" style="width: 250px; height:250px;">
                            {% if question.image %}
                                <a href="{% url 'pybo:detail' question.id %}">
                                     <img src="{{ question.image.url }}" style="width:248px; height:248px;" alt="{{ question.name }}" class="my-3">
                                </a>
                            {% endif %}
                        </div>
                         <div class="card" style="width: 250px">
                            <p class="price">가격: {{ question.price }}</p>
                            <p class="user">판매자: {{ question.author.username }}</p>
                            <p>{{ question.create_date|time_since }}</p>
                            <p class="view">조회수:
                                {% if question.view_count > 0 %}
                                    <span class="text-danger small mx-2">{{ question.view_count }}</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}
        {% else %}
            <div class="col">
                <p>질문이 없습니다.</p>
            </div>
        {% endif %}
    </div>
</div>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}